### ISSUE TITLE
draw.io Indonesian interface cannot be changed

### ISSUE THREAD

**Issue by heviiguy** [marc0l92/joplin-plugin-drawio#1]
Beneficial plug in but, when draw.io is launched, an Indonesial GUI appears. Changing to a prefered language does not work as when the program is restarted, the original Indonesian interface reappears.  

Mac OS 10.15.7
Joplin  2.7.13
Emoji Plug-in 1.0

**Comment by ashcoft** [comment]
same with me

**Comment by jnslmk** [comment]
You can change it in the Joplin settings Tools -> Options -> Draw.io -> Theme: Language. After restarting Joplin the changes took effect for me.

I  suggest setting the default language to English though.

**Comment by marc0l92** [comment]
I released a new version of this plugin that sets the default version to English as suggested by @jnslmk .
Please update the plugin to 0.1.2

**Comment by jnslmk** [comment]
Thank you for fixing this and thanks for the plugin!
