### ISSUE TITLE
canvas scroll not correctly when I drag element

### ISSUE THREAD

**Issue by pansinm** [marc0l92/joplin-plugin-drawio#13]
Canvas scroll not correctly when I drag element. 

![录屏_joplin_20220721135323](https://user-images.githubusercontent.com/5510633/180139739-0c36bd86-0b1c-43d8-bf3b-3149cb1b7b12.gif)

It's seems correctly when i set `data` to `undefined` in below code

![图片](https://user-images.githubusercontent.com/5510633/180140487-3847d1ee-ae9b-4459-8d1e-4536ff6720d9.png)

**Comment by marc0l92** [comment]
I'm aware of this issue, but I was not able to fix it... and then I moved to Obsidian.
I can try the fix you are proposing and integrating in the next version even if it is a strange work around.

**Comment by shandowc** [comment]
this has been fixed by https://github.com/marc0l92/joplin-plugin-drawio/pull/12 @marc0l92

**Comment by marc0l92** [comment]
Thanks
