### ISSUE TITLE
Inserting diagram from Tools menu only creates small white rectangle

### ISSUE THREAD

**Issue by stricklandrbls** [marc0l92/joplin-plugin-drawio#14]
Like the title says, when I create a draw.io diagram from the Tools menu and click save, only a white small rectangle appears. Whenever I try to resize the image it does nothing. MD shows `<img src="data:;base64, <svg width=" 1700"="" height="1536" xmlns="http://www.w3.org/2000/svg">  " />` where the diagram should be.

**Comment by zickzackzuck** [comment]
Same Problem here: If I want to open the File, the Program does nothing.

**Comment by ou-li** [comment]
I  have stumbled accross this, too.
Make sure you're insterting the diagram in Markdown Editor, not the Preview.
![grafik](https://user-images.githubusercontent.com/7612981/188495831-b1199369-c728-4c2f-b9bf-4da442a81e1e.png)
