### ISSUE TITLE
Custom DrawIO server

### ISSUE THREAD

**Issue by Thulium-Drake** [marc0l92/joplin-plugin-drawio#4]
Hi there,

Thanks for the great plugin! I was wondering if it's possible to set the DrawIO URL somewhere, as that can come in very handy when you can't access the Internet, but you do have access to a local DrawIO server.

Thanks!

**Comment by marc0l92** [comment]
Option available starting from v1.4.0

**Comment by Thulium-Drake** [comment]
Thanks for making this!
