### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by noteverlong** [marc0l92/joplin-plugin-drawio#6]
In the webdav synchronization environment, after using the plugin to modify the graphics, the modified graphics cannot be synchronized normally

**Comment by noteverlong** [comment]
Is it possible to solve the problem by modifying the drawio id = every time? 

<drawio id="](:/92b9fc079a314dcd98fa72231e2e3281)"/>

**Comment by noteverlong** [comment]
drawio id="](:/92b9fc079a314dcd98fa72231e2e3281)"

**Comment by marc0l92** [comment]
I implemented this suggestion in the version 2.0

**Comment by noteverlong** [comment]
> I implemented this suggestion in the version 2.0

Thanks a lot!
