### ISSUE TITLE
Zoom automatically resets to 100%

### ISSUE THREAD

**Issue by rar0ch** [marc0l92/joplin-plugin-drawio#8]
If I zoom in or out and then add or modify an element, the zoom setting automatically resets to 100%.
This doesn't happen on [app.diagrams.net](https://app.diagrams.net/) and is really annoying.

If I comment [this line](https://github.com/marc0l92/joplin-plugin-drawio/blob/master/src/dialog/bootstrap.js#L40) it doesn't happen.

Joplin 2.7.15
Draw.io plugin 2.0.0 (default settings)

Other than that, this plugin is super helpful, thanks for creating it :)

**Comment by shandowc** [comment]
this has been fixed by https://github.com/marc0l92/joplin-plugin-drawio/pull/12 @marc0l92

**Comment by marc0l92** [comment]
Thanks
